include_recipe('particle-base::packages')
include_recipe('particle-base::user')
include_recipe('particle-base::compilers')
include_recipe('particle-base::directories')
include_recipe('particle-base::scripts')
include_recipe('particle-base::particle_cli_ng')
