---
driver:
  name: docker
  privileged: true

provisioner:
  name: policyfile_zero
  require_chef_omnibus: '12.13.37' # true to use latest

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: debian-8.2

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
