name 'particle-base'
maintainer 'Joe Goggins'
maintainer_email 'joe@particle.io'
license 'all_rights'
description 'Installs/Configures useful tools for programming, testing, and interacting with Particle Devices (https://www.particle.io)'
# long_description ''
version '0.1.0'
